import ../src/clay

template abiType(label: string; T: typedesc) =
  echo "T ", label, " ", sizeof(T), " ", alignof(T)

template abiField(label: string; T: typedesc; field: untyped) =
  echo "F ", label, " ", offsetOf(T, field)

abiType("Clay_String", Clay_String)
abiType("Clay_StringSlice", Clay_StringSlice)
abiType("Clay_Arena", Clay_Arena)
abiType("Clay_Dimensions", Clay_Dimensions)
abiType("Clay_Vector2", Clay_Vector2)
abiType("Clay_Color", Clay_Color)
abiType("Clay_BoundingBox", Clay_BoundingBox)
abiType("Clay_ElementId", Clay_ElementId)
abiType("Clay_ElementIdArray", Clay_ElementIdArray)
abiType("Clay_CornerRadius", Clay_CornerRadius)
abiType("Clay_LayoutDirection", Clay_LayoutDirection)
abiType("Clay_LayoutAlignmentX", Clay_LayoutAlignmentX)
abiType("Clay_LayoutAlignmentY", Clay_LayoutAlignmentY)
abiType("Clay__SizingType", Clay_SizingType)
abiType("Clay_ChildAlignment", Clay_ChildAlignment)
abiType("Clay_SizingMinMax", Clay_SizingMinMax)
abiType("Clay_SizingAxis", Clay_SizingAxis)
abiType("Clay_Sizing", Clay_Sizing)
abiType("Clay_Padding", Clay_Padding)
abiType("Clay__Clay_PaddingWrapper", Clay_Clay_PaddingWrapper)
abiType("Clay_LayoutConfig", Clay_LayoutConfig)
abiType("Clay__Clay_LayoutConfigWrapper", Clay_Clay_LayoutConfigWrapper)
abiType("Clay_TextElementConfigWrapMode", Clay_TextElementConfigWrapMode)
abiType("Clay_TextAlignment", Clay_TextAlignment)
abiType("Clay_TextElementConfig", Clay_TextElementConfig)
abiType("Clay__Clay_TextElementConfigWrapper", Clay_Clay_TextElementConfigWrapper)
abiType("Clay_AspectRatioElementConfig", Clay_AspectRatioElementConfig)
abiType("Clay__Clay_AspectRatioElementConfigWrapper", Clay_Clay_AspectRatioElementConfigWrapper)
abiType("Clay_ImageElementConfig", Clay_ImageElementConfig)
abiType("Clay__Clay_ImageElementConfigWrapper", Clay_Clay_ImageElementConfigWrapper)
abiType("Clay_FloatingAttachPointType", Clay_FloatingAttachPointType)
abiType("Clay_FloatingAttachPoints", Clay_FloatingAttachPoints)
abiType("Clay_PointerCaptureMode", Clay_PointerCaptureMode)
abiType("Clay_FloatingAttachToElement", Clay_FloatingAttachToElement)
abiType("Clay_FloatingClipToElement", Clay_FloatingClipToElement)
abiType("Clay_FloatingElementConfig", Clay_FloatingElementConfig)
abiType("Clay__Clay_FloatingElementConfigWrapper", Clay_Clay_FloatingElementConfigWrapper)
abiType("Clay_CustomElementConfig", Clay_CustomElementConfig)
abiType("Clay__Clay_CustomElementConfigWrapper", Clay_Clay_CustomElementConfigWrapper)
abiType("Clay_ClipElementConfig", Clay_ClipElementConfig)
abiType("Clay__Clay_ClipElementConfigWrapper", Clay_Clay_ClipElementConfigWrapper)
abiType("Clay_BorderWidth", Clay_BorderWidth)
abiType("Clay_BorderElementConfig", Clay_BorderElementConfig)
abiType("Clay__Clay_BorderElementConfigWrapper", Clay_Clay_BorderElementConfigWrapper)
abiType("Clay_TransitionData", Clay_TransitionData)
abiType("Clay_TransitionState", Clay_TransitionState)
abiType("Clay_TransitionProperty", Clay_TransitionProperty)
abiType("Clay_TransitionCallbackArguments", Clay_TransitionCallbackArguments)
abiType("Clay_TransitionEnterTriggerType", Clay_TransitionEnterTriggerType)
abiType("Clay_TransitionExitTriggerType", Clay_TransitionExitTriggerType)
abiType("Clay_TransitionInteractionHandlingType", Clay_TransitionInteractionHandlingType)
abiType("Clay_ExitTransitionSiblingOrdering", Clay_ExitTransitionSiblingOrdering)
abiType("Clay_TransitionElementConfig", Clay_TransitionElementConfig)
abiType("Clay__Clay_TransitionElementConfigWrapper", Clay_Clay_TransitionElementConfigWrapper)
abiType("Clay_TextRenderData", Clay_TextRenderData)
abiType("Clay_RectangleRenderData", Clay_RectangleRenderData)
abiType("Clay_ImageRenderData", Clay_ImageRenderData)
abiType("Clay_CustomRenderData", Clay_CustomRenderData)
abiType("Clay_ClipRenderData", Clay_ClipRenderData)
abiType("Clay_OverlayColorRenderData", Clay_OverlayColorRenderData)
abiType("Clay_BorderRenderData", Clay_BorderRenderData)
abiType("Clay_RenderData", Clay_RenderData)
abiType("Clay_ScrollContainerData", Clay_ScrollContainerData)
abiType("Clay_ElementData", Clay_ElementData)
abiType("Clay_RenderCommandType", Clay_RenderCommandType)
abiType("Clay_RenderCommand", Clay_RenderCommand)
abiType("Clay_RenderCommandArray", Clay_RenderCommandArray)
abiType("Clay_PointerDataInteractionState", Clay_PointerDataInteractionState)
abiType("Clay_PointerData", Clay_PointerData)
abiType("Clay_ElementDeclaration", Clay_ElementDeclaration)
abiType("Clay__Clay_ElementDeclarationWrapper", Clay_Clay_ElementDeclarationWrapper)
abiType("Clay_ErrorType", Clay_ErrorType)
abiType("Clay_ErrorData", Clay_ErrorData)
abiType("Clay_ErrorHandler", Clay_ErrorHandler)

abiField("Clay_String.length", Clay_String, length)
abiField("Clay_String.chars", Clay_String, chars)
abiField("Clay_StringSlice.baseChars", Clay_StringSlice, baseChars)
abiField("Clay_Arena.capacity", Clay_Arena, capacity)
abiField("Clay_Arena.memory", Clay_Arena, memory)
abiField("Clay_ElementId.stringId", Clay_ElementId, stringId)
abiField("Clay_ElementIdArray.internalArray", Clay_ElementIdArray, internalArray)
abiField("Clay_SizingAxis.type", Clay_SizingAxis, `type`)
abiField("Clay_LayoutConfig.layoutDirection", Clay_LayoutConfig, layoutDirection)
abiField("Clay_TextElementConfig.textAlignment", Clay_TextElementConfig, textAlignment)
abiField("Clay_FloatingElementConfig.attachPoints", Clay_FloatingElementConfig, attachPoints)
abiField("Clay_FloatingElementConfig.clipTo", Clay_FloatingElementConfig, clipTo)
abiField("Clay_ClipElementConfig.childOffset", Clay_ClipElementConfig, childOffset)
abiField("Clay_BorderWidth.betweenChildren", Clay_BorderWidth, betweenChildren)
abiField("Clay_TransitionCallbackArguments.current", Clay_TransitionCallbackArguments, current)
abiField("Clay_TransitionCallbackArguments.properties", Clay_TransitionCallbackArguments, properties)
abiField("Clay_TransitionElementConfig.enter", Clay_TransitionElementConfig, enter)
abiField("Clay_TransitionElementConfig.exit", Clay_TransitionElementConfig, exit)
abiField("Clay_TextRenderData.lineHeight", Clay_TextRenderData, lineHeight)
abiField("Clay_ImageRenderData.imageData", Clay_ImageRenderData, imageData)
abiField("Clay_CustomRenderData.customData", Clay_CustomRenderData, customData)
abiField("Clay_RenderCommand.renderData", Clay_RenderCommand, renderData)
abiField("Clay_RenderCommand.commandType", Clay_RenderCommand, commandType)
abiField("Clay_ScrollContainerData.found", Clay_ScrollContainerData, found)
abiField("Clay_ElementData.found", Clay_ElementData, found)
abiField("Clay_RenderCommandArray.internalArray", Clay_RenderCommandArray, internalArray)
abiField("Clay_PointerData.state", Clay_PointerData, state)
abiField("Clay_ElementDeclaration.transition", Clay_ElementDeclaration, transition)
abiField("Clay_ElementDeclaration.userData", Clay_ElementDeclaration, userData)
abiField("Clay_ErrorData.userData", Clay_ErrorData, userData)
abiField("Clay_ErrorHandler.userData", Clay_ErrorHandler, userData)
